
import { PHEVFormData } from '../types/phevDiagnosticForm';

export const getInitialPHEVFormData = (): PHEVFormData => ({
  customerName: '',
  vin: '',
  roNumber: '',
  vehicleMake: '',
  model: '',
  mileage: '',
  fuelType: '',
  fuelSource: '',
  petrolVsEvUsage: '',
  fuelEconomyChange: '',
  fuelEconomyDetails: '',
  batteryCharging: '',
  batteryChargingDetails: '',
  chargerType: '',
  aftermarketCharger: '',
  aftermarketDetails: '',
  evRangeExpected: '',
  evRangeDetails: '',
  excessiveIceOperation: '',
  iceOperationDetails: '',
  usualChargeLevel: '',
  dcFastFrequency: '',
  dcFastDuration: '',
  chargeRateDrop: '',
  chargeRateDetails: '',
  switchingLags: '',
  switchingDetails: '',
  engineStartEVMode: '',
  engineStartDetails: '',
  abnormalVibrations: '',
  vibrationsDetails: '',
  accelerationIssues: '',
  accelerationDetails: '',
  engineSound: '',
  engineSoundDetails: '',
  burningSmell: '',
  burningSmellDetails: '',
  misfires: '',
  misfiresDetails: '',
  underbodyNoise: '',
  underbodyDetails: '',
  roadConditionNoises: '',
  roadConditionDetails: '',
  hvacEffectiveness: '',
  hvacDetails: '',
  fanSounds: '',
  fanDetails: '',
  temperatureRegulation: '',
  temperatureDetails: '',
  fuelConsumption: '',
  fuelConsumptionDetails: '',
  averageElectricRange: '',
  infotainmentGlitches: '',
  infotainmentDetails: '',
  otaUpdates: '',
  brokenFeatures: '',
  brokenFeaturesDetails: '',
  lightFlicker: '',
  lightFlickerDetails: '',
  smoothRegen: '',
  smoothRegenDetails: '',
  regenStrength: '',
  regenStrengthDetails: '',
  decelerationNoises: '',
  decelerationNoisesDetails: '',
  towingIssues: '',
  towingDetails: '',
  heavyLoadBehavior: '',
  heavyLoadDetails: '',
  regularModes: [],
  inconsistentPerformance: '',
  inconsistentDetails: '',
  sportModePower: '',
  sportModeDetails: '',
  ecoEvModeLimit: '',
  ecoEvModeDetails: '',
  modeNoise: '',
  modeNoiseDetails: '',
  modeWarnings: '',
  modeWarningsDetails: '',
  temperatureDuringIssue: '',
  vehicleParked: '',
  timeOfDay: '',
  hvacWeatherDifference: '',
  hvacWeatherDetails: '',
  rangeRegenTemp: '',
  rangeRegenDetails: '',
  moistureChargingPort: '',
  uploadedFiles: []
});

export const savePHEVFormData = (formData: PHEVFormData) => {
  const savedRecords = JSON.parse(localStorage.getItem('phevDiagnosticRecords') || '[]');
  const newRecord = {
    id: Date.now().toString(),
    ...formData,
    createdAt: new Date().toISOString(),
    technician: JSON.parse(localStorage.getItem('evDiagUser') || '{}').username
  };
  
  savedRecords.push(newRecord);
  localStorage.setItem('phevDiagnosticRecords', JSON.stringify(savedRecords));
  
  return newRecord.id;
};
