// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drqkmdkagyrkdkfhfuwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRycWttZGthZ3lya2RrZmhmdXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjIzMTMsImV4cCI6MjA2NDUzODMxM30.6nKiSM9Fbb9ga8X5r4SG43W6cPbX75nh2gvF0T1DJyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);